[build]
  base = "frontend"
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://tradex-api.glitch.me"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
